apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ hengsheng }}
  name: {{ APP_NAME }}-aqwsedrf
  labels:
    app: {{ APP_NAME }}-aqwsedrf
spec:
  selector:
    matchLabels:
      app: {{ APP_NAME }}-aqwsedrf
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}-aqwsedrf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
                - matchExpressions:
                  - key: {{ sit1 }}
                    operator: In
                    values:
                      - {{ beijingfh }}
      initContainers:
        - name: init-myapp
          image: 103.160.119.30/daocloud/busybox:v3
          command: ['sh']
          args: ['-c', 'chown -R gaps.gaps /img; chown -R gaps.gaps /logs']
          volumeMounts:
            - mountPath: /logs
              name: app-logs
            - mountPath: /img
              name: app-imgs
      imagePullSecrets:
      	- name: images-103.160.119.30
      containers:
        - image: {{ aqwsedrf.image }}
          name: {{ APP_NAME }}-aqwsedrf
          securityContext:
            runAsUser: 810
          resources:
            requests:
              memory: "0"
              cpu: "0"
            limits:
              memory: "0"
              cpu: "0"
          ports:
            - containerPort: 90800
          env:
            - name: SW_AGENT_NAME
              value: {{ APP_NAME }}-aqwsedrf
            - name: APOLLO_APP_ID
              value: {{ apollo-config-group }}
            - name: oid
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DCE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  
          envFrom:
            - configMapRef:
                name: dmp-user-config
          livenessProbe:
            tcpSocket:
              port: 90800
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 90800
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: app-imgs
              mountPath: /aqwsedrf/data
            - name: app-logs
              mountPath: /logs
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: app-logs
          hostPath:
            path: /data/aqwsedrf/aqwsedrf-log
        - name: app-imgs
          hostPath:
            path: /data/aqwsedrf/aqwsedrf-data